# Some Linux distros come with meh DE's, this fixes that.

- name: Workstation | Linux | Software | GNOME | Bypass for other other OS's
  shell: which htop
  register: gnome_install
  when: ansible_distribution not in ("Parrot OS")

- name: Workstation | Linux | Software | GNOME | Check (Parrot OS Only)
  shell: which gdm3
  register: gnome_install
  when: ansible_distribution in ("Parrot OS")
  ignore_errors: true

- debug:
    var: gnome_install

- name: Workstation | Linux | Software | GNOME | Install
  package:
    name: 
      - gnome 
      - gdm3
    state: present
  when: gnome_install is defined and gnome_install.failed

- name: Workstation | Linux | Software | GNOME | Note Before Exiting
  debug:
    msg: "You will need to run `dpkg-reconfigure gdm3` to ensure gdm3 is selected."
  when: gnome_install is defined and gnome_install.failed

- name: Workstation | Linux | Software | GNOME | Exiting
  shell: exit 1
  when: gnome_install is defined and gnome_install.failed
