---
# Harmonize my systems rather than doing everything manually. :)
- hosts: localhost
  connection: local
  become: true

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/flatpaks.yml
