---
# Harmonize my systems rather than doing everything manually. :)

# Everything
- hosts: localhost
  connection: local
  become: true  

  pre_tasks:
    - include: facts/filesystem_names.yml
    - include: facts/package_names.yml
    - include: facts/service_names.yml

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/harden.yml


# Desktops and laptops
- hosts: workstation
  become: true

  tasks:
    - include: tasks/flatpaks.yml


# Run hardness checks
- hosts: all
  become: true

  tasks:
    - include: tasks/hardness_check_lynis.yml