---
# Harmonize my systems rather than doing everything manually. :)
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Software
    package: 
      name:
      - htop
      - neofetch
      - sshfs
      update_cache: yes
