---
# Harmonize my systems rather than doing everything manually. :)
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Install Requirements
    shell: ansible-galaxy install -r requirements.yml 

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
