---
# Harmonize my systems rather than doing everything manually. :)

# Everything
- name: Initial Setup
  hosts: all, localhost
  connection: local
  become: true  

  pre_tasks:
    - include: facts/filesystem_names.yml
    - include: facts/package_names.yml
    - include: facts/service_names.yml
    - include: facts/user_names.yml

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/harden.yml
      ignore_errors: yes


# Desktops and laptops
- name: UI Setup
  hosts: workstation
  connection: local
  become: true

  tasks:
    - include: tasks/flatpaks.yml
      when: ansible_distribution != "FreeBSD"

  tasks:
    - include: tasks/freebsd_gui.yml
      when: ansible_distribution == "FreeBSD"


# Run hardness checks
- name: Hardening Check
  hosts: all, localhost
  connection: local
  become: true

  tasks:
    - include: tasks/hardness_check_lynis.yml