---
# Harmonize my systems rather than doing everything manually. :)

# Everything
- name: Initial Setup
  hosts: all, localhost
  connection: local
  become: true  

  pre_tasks:
    - include_tasks: facts/system.yml
    - include_tasks: facts/package.yml
    - include_tasks: facts/service.yml
    - include_tasks: facts/user.yml

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/harden.yml
      ignore_errors: yes


# Workstations
- name: UI Setup
  hosts: workstation
  connection: local
  become: true

  tasks:
    - include_tasks: tasks/flatpaks.yml
      when: ansible_system == "Linux" and
            flatpak_distro == yes
    - shell: echo "Not implemented yet. :("
      when: ansible_system == "Linux" and
            flatpak_distro == no
    - include_tasks: tasks/freebsd_gui.yml
      when: ansible_system == "FreeBSD"


# Run Hardness Checks
- name: Hardening Check
  hosts: all, localhost
  connection: local
  become: true

  tasks:
    - include_tasks: tasks/hardness_check_lynis.yml