---
# Harmonize my systems rather than doing everything manually. :)



- hosts: all
  connection: local
  become: true
  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/harden.yml

- hosts: workstation
  become: true
  tasks:
    - include: tasks/flatpaks.yml
