---
# Harmonize my systems rather than doing everything manually. :)

# Everything
- name: Initial Setup
  hosts: all, localhost
  connection: local
  become: true  

  pre_tasks:
    - include: facts/system.yml
    - include: facts/package.yml
    - include: facts/service.yml
    - include: facts/user.yml

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/harden.yml
      ignore_errors: yes


# Workstations
- name: UI Setup
  hosts: workstation
  connection: local
  become: true

  tasks:
    - include: tasks/flatpaks.yml
      when: ansible_system == "Linux" and
            "{{ flatpak_distro }} == yes"
    - shell: echo "Not implemented yet. :("
      when: ansible_system == "Linux" and
            "{{ flatpak_distro }} == no"
    - include: tasks/freebsd_gui.yml
      when: ansible_system == "FreeBSD"


# Run Hardness Checks
- name: Hardening Check
  hosts: all, localhost
  connection: local
  become: true

  tasks:
    - include: tasks/hardness_check_lynis.yml