---
# System tasks for mining machines.

## Performance ##

- name: Miner | Account Management | Cron | Ansible | Daily Performance Reboot
  cron:
    user: ansible
    name: Daily Performance Reboot
    job: sudo reboot
    special_time: daily
    state: present
    disabled: no


## Security ##

- name: Miner | Account Management | Cron | Ansible | Daily Security Update
  cron:
    user: ansible
    name: Daily Security Update
    job: apt update && apt dist-upgrade -y
    special_time: reboot
    state: present
    disabled: no
  when: ansible_pkg_mgr == "apt"