---
# Jobs for miners.

- name: Miner | Account Management | Cron | Miner Names
  set_fact:
    miners:
    - { "name": "xmr_stak_cpu", "enabled": ("xmr_stak_cpu" in miner) }
    - { "name": "ethminer",     "enabled": ("ethminer" in miner) }
    #- { "name": "nanominer",    "enabled": ("nanominer" in miner) }
  

- name: Miner | Account Management | Cron | Stop Jobs
  cron:
    user: mfn
    name: "Stop {{ item.name }}"
    minute: "7"
    job: "killall {{ item.name }}.sh"
    state: present
    disabled: "{{ item.enabled }}"
  loop: "{{ miners }}"


- name: Miner | Account Management | Cron | Start Jobs
  cron:
    user: mfn
    name: "Start {{ item.name }}"
    minute: "0-6,8-59"
    job: "ps -ef | grep '{{ item.name }}.sh' | grep -v 'grep' && {{ user_mfn.home }}/{{ item.name }}.sh"
    state: present
    disabled: "{{ not(item.enabled) }}"
  loop: "{{ miners }}"
