- name: Install Flatpak TODO! Make only for workstations
  package:
    name: flatpak
    update_cache: yes

- name: Add Flathub for System
  flatpak_remote:
    name: flathub
    state: present
    method: system
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Remove packages that may come with an OS but are being installed as Flatpak
  package: 
    name:
    - {{ discord[ansible_distribution] }} 
    - {{ thunderbird[ansible_distribution] }} 
    state: absent

- name: Install Discord
  flatpak:
    name: com.discordapp.Discord

- name: Install Shotcut
  flatpak:
    name: org.shotcut.Shotcut

- name: Install Firefox
  flatpak:
    name: org.mozilla.firefox

- name: Install Thunderbird
  flatpak:
    name: org.mozilla.Thunderbird

