- name: Install Lynis
  ansible.builtin.git: 
    repo: https://github.com/CISOfy/lynis
    dest: /usr/local/lynis
    clone: yes
    force: yes

- name: Run Lynis
  ansible.builtin.command:
  args:
    cmd: lynis audit system
    chdir: /usr/local/lynis/
