- name: Install Repo Software
  package: 
    name:
    - htop
    - neofetch
    - sshfs
    update_cache: yes

- name: Install Flatpak Software
  flatpak:
    name: 
      - com.discordapp.Discord
      - org.shotcut.Shotcut
    state: present
