- name: Install Repo Software
  package: 
    name:
    - htop
    - neofetch
    - sshfs
    update_cache: yes

- name: Install Flatpak
  packge:
    name: flatpak

- name: Install Discord
  flatpak:
    name: com.discordapp.Discord

- name: Install Shotcut
  flatpak:
    name: org.shotcut.Shotcut
