---
# Install OpenCL drivers.

- name: Check If Installed
  shell: 'which amdgpu-pro-uninstall'
  register: amdgpu_installed

- name: Folder
  shell: 'mkdir -p Downloads'
  when: amdgpu_installed.stdout == ""

- name: Download
  shell: 'scp ling@leet:InstallFiles/Drivers/amdgpu-pro-20.45-1188099-ubuntu-20.04.tar.xz Downloads/'
  when: amdgpu_installed.stdout == ""

- name: Extract
  shell: 'cd Downloads; tar -xvf amdgpu-pro-20.45-1188099-ubuntu-20.04.tar.xz'
  when: amdgpu_installed.stdout == ""

- name: Install 1 - All
  shell: 'cd Downloads/amdgpu-pro-20.45-1188099-ubuntu-20.04; amdgpu-install -y'
  when: amdgpu_installed.stdout == ""

- name: Install 2 - Pro
  shell: 'cd Downloads/amdgpu-pro-20.45-1188099-ubuntu-20.04; amdgpu-pro-install -y --opencl=pal,legacy'
  when: amdgpu_installed.stdout == ""

- name: Delete
  shell: 'rm -rf Downloads/*'
  when: amdgpu_installed.stdout == ""