---
# Variablize keys in config file.

## Load Config File ##

- name: Miner | Facts | Config File | Download
  shell: "scp {{ file_server }}:{{ config_file_remote }} {{ config_file_local }}; chmod 700 {{ config_file_local }}"

- name: Miner | Facts | Config File | Load Wallets
  set_fact:
    wallet_xmr: "{{ lookup('ini', 'xmr section={{config_section_wallet}} file={{config_file_local}}') }}"
    wallet_eth: "{{ lookup('ini', 'eth section={{config_section_wallet}} file={{config_file_local}}') }}"


## Verify ##

- name: Miner | Facts | Config File | DEBUG
  debug:
    var: "{{ item }}"
  loop: 
    - wallet_xmr
    - wallet_eth


## Clean Up ##

- name: Miner | Facts | Config File | Delete
  shell: "mv {{ config_file_local }} ~/TRASH/"
