---
# Define what the file and folder names should be on each OS.

- name: Set Pop!_OS Desktop Facts
  ansible.builtin.set_fact:
    flatpak_distro: yes
    lynis_install_dir: /usr/local/lynis
    lynis_report: /home/ling/lynis.log
    sudoers_install_dir: /etc/sudoers.d/ansible
    ansible_pull_exec: /usr/bin/ansible-pull
  when: ansible_distribution == "Pop!_OS"


# TODO Needs tested
- name: Set Debian+Ubuntu Server Facts
  ansible.builtin.set_fact:
    flatpak_distro: yes
    lynis_install_dir: /usr/local/lynis
    lynis_report: /root/lynis.log
    sudoers_install_dir: /etc/sudoers.d/ansible
    ansible_pull_exec: /usr/bin/ansible-pull
  when: ansible_distribution in ("Debian","Ubuntu")


- name: Set FreeBSD Facts
  ansible.builtin.set_fact:
    flatpak_distro: no
    lynis_install_dir: /usr/local/lynis
    lynis_report: /root/lynis.log
    sudoers_install_dir: /usr/local/etc/sudoers.d/ansible
    ansible_pull_exec: /usr/local/bin/ansible-pull
  when: ansible_distribution == "FreeBSD"