---
# Define users and groups for each OS

- name: Set Linux User Variables
  ansible.builtin.set_fact:
    root: root
    root_group: root
    ansible: ansible
  when: ansible_distribution == "Pop!_OS" or
        ansible_distribution == "Ubuntu"

- name: Set FreeBSD User Variables
  ansible.builtin.set_fact:
    root: root
    root_group: wheel
    ansible: ansible
  when: ansible_distribution == "FreeBSD"