---
# Define program names per OS for package builtin.
# This is only for Workstation devices with UIs.

- name: Facts | Workstation | Package | Consistent
  set_fact:
    firefox: firefox
    thunderbird: thunderbird
    evolution: evolution
    gnome_tweaks: gnome-tweaks
    dconf_editor: dconf-editor


- name: Facts | Workstation | Package | Pop_OS!
  set_fact:
    flatpak_distro: true
    firefox_esr: firefox
    psutil: python3-psutil
  when: ansible_distribution == "Pop!_OS"


- name: Facts | Workstation | Package | Ubuntu
  set_fact:
    flatpak_distro: true
    firefox_esr: firefox
    psutil: python3-psutil
  when: ansible_distribution == "Ubuntu"


- name: Facts | Workstation | Package | Debian
  set_fact:
    flatpak_distro: true
    firefox_esr: firefox-esr
    psutil: python3-psutil
  when: ansible_distribution == "Debian"


- name: Facts | Workstation | Package | FreeBSD
  set_fact:
    flatpak_distro: false
    firefox_esr: firefox-esr
    psutil: py37-psutil
  when: ansible_system == "FreeBSD"