---
# Define program names per OS for package builtin.
# This is only for Workstation devices with UIs.

- name: Workstation | Facts | Package | Consistent
  set_fact:
    firefox: firefox
    thunderbird: thunderbird
    evolution: evolution
    gnome_tweaks: gnome-tweaks
    dconf_editor: dconf-editor
    appimagelauncher: htop #placeholder
    nfs: nfs-common


- name: Workstation | Facts | Package | Pop_OS!
  set_fact:
    flatpak_distro: true
    firefox_esr: firefox
    psutil: python3-psutil
  when: ansible_distribution == "Pop!_OS"


- name: Workstation | Facts | Package | Ubuntu
  set_fact:
    flatpak_distro: true
    firefox_esr: firefox
    psutil: python3-psutil
  when: ansible_distribution == "Ubuntu"


- name: Workstation | Facts | Package | Debian
  set_fact:
    flatpak_distro: true
    firefox_esr: firefox-esr
    psutil: python3-psutil
  when: ansible_distribution == "Debian"


- name: Workstation | Facts | Package | Arch + Manjaro
  set_fact:
    flatpak_distro: true
    firefox_esr: firefox
    psutil: python-psutil
    appimagelauncher: appimagelauncher
  when: ansible_distribution == "Archlinux"


- name: Workstation | Facts | Package | FreeBSD
  set_fact:
    flatpak_distro: false
    firefox_esr: firefox-esr
    psutil: py37-psutil
  when: ansible_system == "FreeBSD"