---
# Define program names per OS for package builtin.
# This is only for Workstation devices with UIs.

- name: Facts | Workstation | Package | Pop OS
  set_fact:
    firefox: firefox
    firefox_esr: firefox-esr
    thunderbird: thunderbird
    evolution: evolution
  when: ansible_distribution == "Pop!_OS"


- name: Facts | Workstation | Package | Debian and Ubuntu
  set_fact:
    firefox: firefox
    firefox_esr: firefox-esr
    thunderbird: thunderbird
    evolution: evolution
  when: ansible_distribution in ("Debian","Ubuntu")


- name: Facts | Workstation | Package | FreeBSD
  set_fact:
    firefox: firefox
    firefox_esr: firefox-esr
    thunderbird: thunderbird
    evolution: evolution
  when: ansible_system == "FreeBSD"