---
# Install the Nix configuration at github.com/Hyperling/NixOS.
#

- name: General | Software | NixOS | Facts
  set_fact:
    nixos_working_dir: ~/nixos-config-deleteme
    nixos_working_exe: activate.sh

- name: General | Software | NixOS | Install Config Project
  shell: "{{ item }}"
  loop:
    - sh -c "rm -rfv {{ nixos_working_dir }}"
    - "git clone https://github.com/Hyperling/NixOS --branch {{ branch }} {{ nixos_working_dir }}"
    - "chmod 755 {{ nixos_working_dir }}/{{ nixos_working_exe }}"
    - "{{ nixos_working_dir }}/{{ nixos_working_exe }}"
    - sh -c "rm -rfv {{ nixos_working_dir }}"

#  Maybe do home manager here? Or should it be under Workstation? Or maybe
#   this is the spot where I start creating workstation.nix, server.nix, etc.
#- name: General | Software | NixOS | Home Manager? *.nix file management?
#  shell:
#  loop:
#    - ???
#    - ???
