---
# Update the Nix configuration at github.com/Hyperling/NixOS.
# This is also done in setup.sh if ansible is not found.

- name: General | Software | NixOS | Facts
  set_fact:
    nixos_working_dir: ~/nixos-config-deleteme
    nixos_working_exe: activate.sh

- name: General | Software | NixOS | Update Config Project
  shell: "files/scripts/nixos.sh -b {{ branch }}"

#  Maybe do home manager here? Or should it be under Workstation? Or maybe
#   this is the spot where I start creating workstation.nix, server.nix, etc.
#- name: General | Software | NixOS | Home Manager? *.nix file management?
#  shell:
#  loop:
#    - ???
#    - ???
