---

- name: Install Repo Software
  package: 
    name:
    - sudo
    - htop
    - neofetch
    - "{{ sshfs }}"
    - locate
    state: present

- name: Remove Repo Software
  package: 
    name:
    - cowsay # Sorry ;)
    - snapd
    state: absent
