---
# Cross-platform package management.

- name: Repo Cache Refresh
  package:
    update_cache: yes
  when: ansible_pkg_mgr in ["apt", "pacman"]

- name: Install Repo Software
  package: 
    name:
    - htop
    - neofetch
    - "{{ sshfs }}"
    - locate
    state: present

- name: Update Repo Software
  package: 
    name:
    - ansible
    - git
    - sudo
    state: latest

- name: Remove Repo Software
  package: 
    name:
    - cowsay # Sorry ;)
    state: absent

# TODO: Confirm if Ubuntu still uses snap for critical components like GNOME.
- name: Remove Repo Software
  package: 
    name:
    - snapd
    state: absent
  when: ansible_distribution != "Ubuntu"
