---
# Cross-platform package management.

- name: Install Repo Software
  package: 
    name:
    - sudo
    - htop
    - neofetch
    - "{{ sshfs }}"
    - locate
    state: present

- name: Testing Package Cache Refresh
  package:
    update_cache: yes
  when: ansible_os_family in ["Debian", "Ubuntu"]

- name: Testing Apt Cache Refresh
  apt: update_cache=yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Testing Apt Cache Refresh 2
  apt: update_cache=yes
  when: ansible_pkg_mgr = "apt"

- name: Remove Repo Software
  package: 
    name:
    - cowsay # Sorry ;)
    state: absent

# TODO: Confirm if Ubuntu still uses snap for critical UI components like GNOME.
- name: Remove Repo Software
  package: 
    name:
    - snapd
    state: absent
  when: ansible_distribution != "Ubuntu"
