---
# Cross-platform package management.

- name: Install Repo Software
  package: 
    name:
    - sudo
    - htop
    - neofetch
    - "{{ sshfs }}"
    - locate
    state: present

- name: Testing Cache Refresh Conditions for LearnLinuxTV/personal_ansible_desktop_configs Bug1
  package:
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"] or
        ansible_os_family in ["Debian", "Ubuntu"]

- name: Remove Repo Software
  package: 
    name:
    - cowsay # Sorry ;)
    state: absent

# TODO: Confirm if Ubuntu still uses snap for critical UI components like GNOME.
- name: Remove Repo Software
  package: 
    name:
    - snapd
    state: absent
  when: ansible_distribution != "Ubuntu"
