---
# Enable and disable services.

- name: General | Software | Services | Create SSHFS rc.conf Entry (FreeBSD)
  blockinfile:
    path: /etc/rc.conf
    block: |
      fusefs_enable="YES"
    marker: "# {mark} MANAGED BY ANSIBLE | SSHFS"
    state: present
    backup: yes
  when: ansible_system == "FreeBSD"

- name: General | Software | Services | Load SSHFS (FreeBSD)
  shell: kldload fusefs
  args:
    warn: false
  when: ansible_system == "FreeBSD"

- name: General | Software | Services | Disable CUPS Daemon
  service:
    name: "{{ cups }}"
    pattern: "{{ cups_pattern }}"
    state: stopped
    enabled: no

- name: General | Software | Services | Disable CUPS-Browse Daemon
  service:
    name: "{{ cups_browse }}"
    pattern: "{{ cups_browse_pattern }}"
    state: stopped
    enabled: no