---
# Setup swap file on systems without any swap available.
# Must have the swap amount preferred set up in general.ini.

- name: General | Software | Swap
  block:

  - name: General | Software | Swap | Check SWAPON
    shell: "echo 'TBD: {{ swap_block }} {{ swap_count }}'"

  - name: General | Software | Swap | Check FSTAB
    shell: "echo 'TBD: {{ swap_block }} {{ swap_count }}'"

  - name: General | Software | Swap | Check For Swapfiles
    shell: "echo 'TBD: {{ swap_block }} {{ swap_count }}'"

  - name: General | Software | Swap | Install Block
    block:

    - name: General | Software | Swap | Create Swapfile
      shell: "{{ item }}"
      loop:
        - dd if=/dev/zero of={{ swapfile }} bs={{ swap_block }}
            count={{ swap_count }} status=progress
        - chmod 600 {{ swapfile }}
        - mkswap {{ swapfile }}
        - swapon {{ swapfile }}

    # Check for /swapfile line in /etc/fstab and add it if it's missing.
    - name: General | Software | Swap | Add to FSTAB
      lineinfile:
        path: /etc/fstab
        regexp: '^[\#]?{{ swapfile }}'
        line: '{{ swapfile }}'
        state: present
        backup: yes
      when: ansible_distribution != "NixOS"

    # NixOS's swap setup is handled in nixos.yml when ansible.nix is created.

    when: 1 == 0 # TBD: Check if the swapfile does not already exist.

  when: swap_block != false
