---
# Jobs relating to the ansible user.

- name: General | Cron | Ansible | Create Subscriber Job
  cron:
    user: ansible
    name: "Ansible Sync"
    minute: "*/15"
    job: "sudo {{ ansible_pull_exec.stdout }} -o -U https://github.com/Hyperling/ansible.git"
    state: present
    disabled: no

- name: General | Cron | Ansible | Create Heartbeat Job
  cron:
    user: ansible
    name: "Heartbeat Report"
    minute: "*/15"
    job: "date > {{ heartbeat_report }}; chmod 777 {{ heartbeat_report }}"
    state: present
    disabled: no
