---
# Jobs relating to the ansible user.

- name: General | Cron | Ansible | Create Subscriber Job
  cron:
    user: ansible
    name: "Ansible Sync"
    minute: "*/30"
    job: "sudo {{ ansible_pull_exec.stdout }} -o -U {{ repo_local }} --checkout {{ branch }}"
    state: present
    disabled: "{{ 'yes' if no_telem else 'no' }}"

- name: General | Cron | Ansible | Create Forced Weekly Subscriber Job
  cron:
    user: ansible
    name: "Ansible Weekly Forced Sync"
    special_time: weekly
    job: "{{ user_root.home }}/bin/scm.sh"
    state: present
    disabled: "{{ 'yes' if no_telem else 'no' }}"
