---

- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "Ansible Sync"
    minute: "*/15"
    job: "{{ ansible_pull_exec }} -o -U https://github.com/Hyperling/ansible.git"
    state: present
    disabled: no
