---
# Mount network shares.

- name: Workstation | Settings | NFS | Facts (Linux)
  set_fact:
    mount_options: defaults,_netdev
  when: ansible_system == "Linux"

- name: Workstation | Settings | NFS | Facts (FreeBSD)
  set_fact:
    mount_options: rw
  when: ansible_system == "FreeBSD"


- name: Workstation | Settings | NFS | Install (Linux)
  package: 
    name: 
      - "{{ nfs }}"
    state: present
  when: ansible_system == "Linux"

# https://www.unixmen.com/setup-nfs-server-on-freebsd/
- name: Workstation | Settings | NFS | Install (FreeBSD)
  blockinfile:
    path: "{{ rc_conf }}"
    marker: "# {mark} MANAGED BY ANSIBLE | NFS Components"
    block: |
      nfs_server_enable="YES"
      nfs_server_flags="-u -t -n 4"
      rpcbind_enable="YES"
      mountd_flags="-r"
      mountd_enable="YES"
      nfs_client_enable="YES"
      nfs_client_flags="-n 4"
      rpc_lockd_enable="YES"
      rpc_statd_enable="YES"
    create: yes
    backup: yes
  when: ansible_system == "FreeBSD"
