---
# Enable and disable services.

## CUPS ##

- name: General | Software | Services | Enable CUPS Daemon
  service:
    name: "{{ cups }}"
    pattern: "{{ cups_pattern }}"
    state: started
    enabled: yes
  ignore_errors: yes

- name: General | Software | Services | Enable CUPS-Browse Daemon
  service:
    name: "{{ cups_browse }}"
    pattern: "{{ cups_browse_pattern }}"
    state: started
    enabled: yes
  ignore_errors: yes
