---
# Ensure certbot renews certs on time.

- name: Server | Cron | Certbot | Find Executable
  shell: which certbot
  register: certbot

- name: Server | Cron | Certbot | Monthly Renewal
  cron:
    user: root
    name: Monthly Renewal
    job: "{{ certbot.stdout }} renew"
    special_time: weekly
    state: present
    disabled: no
  when: certbot is defined