---
# Cron jobs specific to FreeBSD

- name: General | Cron | Ansible | FreeBSD | Enable Security Update
  cron:
    user: ansible
    name: "Security Update"
    special_time: daily
    job: "sudo freebsd-update cron -t me@hyperling.com"
    state: present
    disabled: no