---
# Nanominer from nanopool.org
# Good documentation that might help with how to do variables.
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html

## Install ##


## Settings ##

- name: Miner | Software | nanominer | Mine with CPU (Optional)
  debug:
    var: nanominer_config.cpu
  when: nanominer_cpu is defined

- name: Miner | Software | nanominer | Mine with GPU (Optional)
  debug:
    var: nanominer_config.gpu
  when: nanominer_gpu is defined

#- name: Miner | Software | nanominer | Mine with GPU (Optional)
#  blockinfile:
#    path: "{{ item }}/.bashrc"
#    block: |
#      watchdog = true
#    marker: '# {mark} MANAGED BY ANSIBLE | Aliases'
#    state: present
#    create: yes
#    backup: yes
#  when: nanominer_gpu is defined

- name: Miner | Software | nanominer | Choose GPUS (Optional)
  debug:
    var: "{{ item }}"
  loop: "{{ nanominer_config.gpus }}"
  when: nanominer_gpus is defined