---
# Nanominer from nanopool.org

## Install ##


## Settings ##

- name: Miner | Software | nanominer | Mine with CPU (Optional)
  debug:
    var: nanominer_config.cpu
  when: nanominer_config.cpu is defined

- name: Miner | Software | nanominer | Mine with GPU (Optional)
  debug:
    var: nanominer_config.gpu
  when: nanominer_config.gpu is defined

#- name: Miner | Software | nanominer | Mine with GPU (Optional)
#  blockinfile:
#    path: "{{ item }}/.bashrc"
#    block: |
#      watchdog = true
#    marker: '# {mark} MANAGED BY ANSIBLE | Aliases'
#    state: present
#    create: yes
#    backup: yes
#  loop: "{{ nanominer_config.gpu }}"
#  when: nanominer_config.gpu is defined

- name: Miner | Software | nanominer | Choose GPUS (Optional)
  debug:
    var: "{{ item }}"
  loop: "{{ nanominer_config.gpus }}"
  when: nanominer_config.gpus is defined