---
# Create file to easily push git changes and call SCM.

- name: General | Scripts | Root | scm.sh
  blockinfile:
    path: "{{ user_root.home }}/scm.sh"
    block: |
      # 20210211 - Make life easier!
      ssh ling@leet "cd Code/Ansible/ansible-pull; git push"
      time curl https://scm.hyperling.com | bash
    marker: '{mark}'
    marker_begin: "#!{{ bash_exec.stdout }}"
    marker_end: "exit 0"
    state: present
    create: yes
    backup: yes

- name: General | Scripts | Root | scm.sh Permissions
  file: 
    path: "{{ user_root.home }}/scm.sh"
    mode: '0755'