---
# Create file to easily push git changes and call SCM.

- name: General | Scripts | Root | scm.sh
  blockinfile:
    path: /root/scm.sh
    block: |
      #!{{ bash_exec.stdout }}
      # 20210211 - Make life easier!
      ssh ling@leet "cd Code/Ansible/ansible-pull; git push"
      curl https://scm.hyperling.com | bash
    marker: ''
    state: present
    create: yes
    backup: yes

- name: General | Scripts | Root | scm.sh Permissions
  file: 
    path: /root/scm.sh
    mode: '0755'