---
# Create file to easily push git changes and call SCM.

- name: General | Scripts | User | scm.sh
  blockinfile:
    path: "{{ user_user.home }}/bin/scm.sh"
    block: |
      # 20210211 - Make life easier!
      push.sh
      time curl https://scm.hyperling.com | sudo bash
    marker: '{mark}'
    marker_begin: "#!{{ bash_exec.stdout }}"
    marker_end: "exit 0"
    state: present
    create: yes

- name: General | Scripts | User | scm.sh Permissions
  file: 
    path: "{{ user_user.home }}/bin/scm.sh"
    mode: '0755'


- name: General | Scripts | User | push.sh
  blockinfile:
    path: "{{ user_user.home }}/bin/push.sh"
    block: |
      # 20210215 - Make life even easier!
      ssh {{ user }}@leet "cd Code/Ansible/ansible-pull; git push"
    marker: '{mark}'
    marker_begin: "#!{{ bash_exec.stdout }}"
    marker_end: "exit 0"
    state: present
    create: yes

- name: General | Scripts | User | push.sh Permissions
  file: 
    path: "{{ user_user.home }}/bin/push.sh"
    mode: '0755'


- name: General | Scripts | User | scm-dev.sh
  blockinfile:
    path: "{{ user_user.home }}/bin/scm-dev.sh"
    block: |
      # 20210713 - Make life easier for development!
      
      ## Variables ##

      # Use a specific branch if it was asked for.
      branch="dev"
      if [[ $1 != "" ]]; then
        branch="$1"
      fi


      ## Main ##

      push.sh
      time sudo {{ ansible_pull_exec.stdout }} -U {{ repo_github }} --checkout $branch

    marker: '{mark}'
    marker_begin: "#!{{ bash_exec.stdout }}"
    marker_end: "exit 0"
    state: present
    create: yes

- name: General | Scripts | User | scm-dev.sh Permissions
  file: 
    path: "{{ user_user.home }}/bin/scm-dev.sh"
    mode: '0755'


- name: General | Scripts | User | scm-local.sh
  blockinfile:
    path: "{{ user_user.home }}/bin/scm-local.sh"
    block: |
      # 20220312 - Make life easier for development! Especially when Github can't be reached.
      
      ## Variables ##


      ## Main ##

      time sudo ansible-playbook /mnt/leet/Code/Ansible/ansible-pull/local.yml

    marker: '{mark}'
    marker_begin: "#!{{ bash_exec.stdout }}"
    marker_end: "exit 0"
    state: present
    create: yes

- name: General | Scripts | User | scm-local.sh Permissions
  file: 
    path: "{{ user_user.home }}/bin/scm-local.sh"
    mode: '0755'
