---
# Create file to easily push git changes and call SCM.

- name: General | Scripts | User | scm.sh
  blockinfile:
    path: "{{ user_user.home }}/bin/scm.sh"
    block: |
      # 20210211 - Make life easier!
      git clone {{ repo_github }} ansible-pull
      ansible-pull/setup.sh
      mv ansible-pull ~/TRASH/
    marker: '{mark}'
    marker_begin: "#!{{ bash_exec.stdout }}"
    marker_end: "exit 0"
    state: present
    create: yes

- name: General | Scripts | User | scm.sh Permissions
  file:
    path: "{{ user_user.home }}/bin/scm.sh"
    mode: '0755'


- name: General | Scripts | User | scm-dev.sh
  blockinfile:
    path: "{{ user_user.home }}/bin/scm-dev.sh"
    block: |
      # 20210713 - Make life easier for development!

      ## Variables ##

      # Use a specific branch if it was asked for.
      branch="dev"
      if [[ $1 != "" ]]; then
        branch="$1"
      fi

      ## Main ##

      time sudo {{ ansible_pull_exec.stdout }} -U {{ repo_github }} --checkout $branch

    marker: '{mark}'
    marker_begin: "#!{{ bash_exec.stdout }}"
    marker_end: "exit 0"
    state: present
    create: yes

- name: General | Scripts | User | scm-dev.sh Permissions
  file:
    path: "{{ user_user.home }}/bin/scm-dev.sh"
    mode: '0755'
