---
# Provide FreeBSD with a DE.

- name: Workstation | FreeBSD | GUI | Install UI Components
  package: 
    name:
    - xorg
    - gnome3
    - "{{ firefox_esr }}"
    - "{{ thunderbird }}"
    - vscode
    - gimp
    state: present

- name: Workstation | FreeBSD | GUI | Uninstall Bloat
  package: 
    name:
    - "{{ firefox }}"
    - "{{ evolution }}"
    state: absent

- name: Workstation | FreeBSD | GUI | Create rc.conf Entries
  blockinfile:
    path: /etc/rc.conf
    marker: "# {mark} MANAGED BY ANSIBLE | GUI Components"
    block: |
      dbus_enable="YES"
      hald_enable="YES"
      gnome_enable="YES"
      gdm_enable="YES"
    backup: yes

- name: Workstation | FreeBSD | GUI | Create proc fstab Entry
  lineinfile:
    path: /etc/fstab
    regexp: '^proc'
    line: proc            /proc           procfs  rw      0       0
    state: absent
    backup: yes

- name: Workstation | FreeBSD | GUI | Create proc fstab Comment
  lineinfile:
    path: /etc/fstab
    regexp: '^# MANAGED BY ANSIBLE | Leet Share'
    line: '# MANAGED BY ANSIBLE | Leet Share'
    state: absent
    insertbefore: '^proc'

- name: Workstation | FreeBSD | GUI | Create fstab Entries
  blockinfile:
    path: /etc/fstab
    block: |
      proc            /proc           procfs  rw      0       0
    marker: '# {mark} MANAGED BY ANSIBLE | GUI Components'
    state: present
    backup: yes

- name: Workstation | FreeBSD | GUI | Mount All
  shell: mount -a
  args:
    warn: false
