---
# Tasks related to starting ansible-pull
# EG: Start timer, kill conflicting jobs, etc

- name: General | Start | Ansible Pull Report | Start File
  shell: "echo 'START' > {{ ansible_pull_report }}"
  when: leet_drive_details.stat.exists

- name: General | Start | Ansible Pull Report | Make Viewable (SSHFS)
  file:
    path: "{{ ansible_pull_report }}"
    mode: '0777'
  when: leet_drive_details.stat.exists

- name: General | Start | Ansible Pull Report | Add Date Entry
  shell: "date >> {{ ansible_pull_report }}"
  when: leet_drive_details.stat.exists