---
# Cron jobs specific to Linux

- name: General | Cron | Ansible | Linux | Update System Flatpaks
  cron:
    user: ansible
    name: "Update System Flatpaks"
    special_time: hourly
    job: "sudo flatpak update"
    state: present
    disabled: no
  when: flatpak_distro

- name: General | Cron | Ansible | Linux | Update User Flatpaks
  cron:
    user: ansible
    name: "Update User Flatpaks"
    special_time: hourly
    job: "sudo -u ling flatpak update"
    state: present
    disabled: no
  when: flatpak_distro