---
# Ensure certbot is installed.

- name: Server | Software | Certbot | FreeBSD
  package: 
    name:
      - py37-certbot
      - py37-certbot-nginx
    state: present
  when: ansible_distribution == "FreeBSD"

- name: Server | Software | Certbot | Apt
  package: 
    name:
      - certbot
      - python3-certbot-nginx
    state: present
  when: ansible_pkg_mgr == "apt"
