---
# Install a Gitlab server for hosting software projects.
# https://about.gitlab.com/install/#ubuntu

## Install ##

- name: Server | Software | GitLab | Check
  shell: which gitlab-ee
  ignore_errors: yes
  register: gitlab_installed

- name: Server | Software | GitLab | Pre-Reqs
  package:
    update_cache: yes
    name: 
      - curl 
      - openssh-server 
      - ca-certificates 
      - tzdata 
      - perl
#      - postfix
    state: present 
  when:  gitlab_installed.failed
  
- name: Server | Software | GitLab | Add Repo
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
  when:  gitlab_installed.failed

- name: Server | Software | GitLab | Install
  shell: EXTERNAL_URL="http://gitlab.{{ domain }}" apt install gitlab-ee
  when:  gitlab_installed.failed

- name: Server | Software | GitLab | Get Password
  shell: cat /etc/gitlab/initial_root_password
  register: gitlab_passwd
  when:  gitlab_installed.failed

- name: Server | Software | GitLab | Print Password
  debug: 
    name: gitlab_passwd
  when:  gitlab_installed.failed

- name: Server | Software | GitLab | Exit For Configuration
  shell: exit 0
  when:  gitlab_installed.failed


## Configuration ##
# https://docs.gitlab.com/ee/install/next_steps.html

- name: Server | Software | GitLab | TBD
  shell: echo "hooray" # TBD
  when: not gitlab_installed.failed