---
# Install everything needed for a Grafana subsite.
# https://grafana.com/docs/grafana/latest/getting-started/getting-started/

## Pre-reqs ##

- name: Server | Grafana | Pre-Requirements | Install
  package: 
    name: 
      - apt-transport-https
      - software-properties-common
      - wget
    state: present

## Install ##

- name: Server | Grafana | Install | Add Repo
  shell: '{{ item }}'
  loop:
    - wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
    - echo "deb https://packages.grafana.com/oss/deb stable main" | tee /etc/apt/sources.list.d/grafana.list
    - apt update

- name: Server | Grafana | Install | Main
  package: 
    name: 
      - grafana
    state: present

## Configure ##

- name: Server | Grafana | Configure
  shell: '{{ item }}'
  loop:
    - systemctl daemon-reload
    - systemctl enable grafana-server
    - systemctl start grafana-server

## SMTP ##
# TODO allow server to send mail for invites, alerting, and password resets.