---
# Define program names per OS for package builtin.
# This file is for ALL systems and should not include UI components.

- name: Facts | Workstation | Package | Pop OS
  set_fact:
    sshfs: sshfs
    locate: locate
  when: ansible_distribution == "Pop!_OS"


- name: Facts | Workstation | Package | Debian and Ubuntu
  set_fact:
    sshfs: sshfs
    locate: locate
  when: ansible_distribution in ("Debian","Ubuntu")


- name: Facts | Workstation | Package | FreeBSD
  set_fact:
    sshfs: fusefs-sshfs
    locate: htop # This is just a placeholder to prevent errors
  when: ansible_system == "FreeBSD"