---
# Define program names per OS for package builtin.

- name: Set Pop OS Package Names
  set_fact:
    firefox: firefox-esr
    thunderbird: thunderbird
    evolution: evolution
    sshfs: sshfs
    locate: locate
  when: ansible_distribution == "Pop!_OS"


- name: Set Debian and Ubuntu Package Names
  set_fact:
    firefox: firefox-esr
    thunderbird: thunderbird
    evolution: evolution
    sshfs: sshfs
    locate: locate
  when: ansible_distribution in ("Debian","Ubuntu")


- name: Set FreeBSD Package Names
  set_fact:
    firefox: firefox-esr
    thunderbird: thunderbird
    evolution: evolution
    sshfs: fusefs-sshfs
    locate: ""
  when: ansible_distribution == "FreeBSD"