---
# Define program names for package builtin.
# This file is for ALL systems and should not include UI components.

- name: Facts | General | Package | apt
  set_fact:
    sshfs: sshfs
    locate: locate
    gnome_tweaks: gnome-tweaks
    dconf_editor: dconf-editor
  when: ansible_pkg_mgr == "apt"
  

- name: Facts | General | Package | FreeBSD
  set_fact:
    sshfs: fusefs-sshfs
    locate: htop # Placeholder to prevent errors. locate builtin FreeBSD.
    gnome_tweaks: gnome-tweaks
    dconf_editor: dconf-editor
  when: ansible_system == "FreeBSD"