---
# Define program names per OS for package builtin.
# This file is for ALL systems and should not include UI components.

- name: Set Pop OS Package Names
  set_fact:
    sshfs: sshfs
    locate: locate
  when: ansible_distribution == "Pop!_OS"


- name: Set Debian and Ubuntu Package Names
  set_fact:
    sshfs: sshfs
    locate: locate
  when: ansible_distribution in ("Debian","Ubuntu")


- name: Set FreeBSD Package Names
  set_fact:
    sshfs: fusefs-sshfs
    locate: htop # This is just a placeholder to prevent errors
  when: ansible_system == "FreeBSD"