---
# Define program names for package builtin.
# This file is for ALL systems and should not include UI components.

- name: Facts | Workstation | Package | apt
  set_fact:
    sshfs: sshfs
    locate: locate
  when: ansible_pkg_mgr == "apt"
  

- name: Facts | Workstation | Package | FreeBSD
  set_fact:
    sshfs: fusefs-sshfs
    locate: htop # Placeholder to prevent errors. locate builtin FreeBSD.
  when: ansible_system == "FreeBSD"