---
# Definitions for service management.

- name: General | Facts | Service | All
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
    sshd: sshd
    sshd_pattern: sshd
    sshd_config: /etc/ssh/sshd_config
    crond: cron
    crond_pattern: cron
    acpi: acpid
    acpi_pattern: acpid
    bluetooth: bluetooth
    bluetooth_pattern: bluetooth

- name: General | Facts | Service | Arch Linux
  set_fact:
    crond: cronie
    crond_pattern: cronie
  when: ansible_distribution in ("Archlinux")

- name: General | Facts | Service | Fedora
  set_fact:
    crond: crond
    crond_pattern: crond
  when: ansible_distribution in ("Fedora")

- name: General | Facts | Service | Ubuntu Linux
  set_fact:
    sshd: ssh
    sshd_pattern: ssh
  when: ansible_distribution == "Ubuntu"
