---
# Definitions for service management.

- name: General | Facts | Service | All
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
    sshfs_leet_cmd: "sshfs {{ leet_ssh }}: /mnt/leet -o allow_other,_netdev"
    sshd: sshd
    sshd_pattern: sshd
    sshd_config: /etc/ssh/sshd_config
    crond: cron
    crond_pattern: cron


#- name: General | Facts | Service | Linux
#  set_fact:
#  when: ansible_system == "Linux"


- name: General | Facts | Service | Linux
  set_fact:
    crond: cronie
    crond_pattern: cronie
  when: ansible_distribution == "Archlinux"


- name: General | Facts | Service | Non-FreeBSD
  set_fact:
    load_fusefs: "echo ''"
  when: ansible_system != "FreeBSD"

- name: General | Facts | Service | FreeBSD
  set_fact:
    load_fusefs: "kldload fusefs"
  when: ansible_system == "FreeBSD"