---
# Definitions for service management.

- name: General | Facts | Service | All
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
    sshd: sshd
    sshd_pattern: sshd
    sshd_config: /etc/ssh/sshd_config
    crond: cron
    crond_pattern: cron
    acpi: acpid
    acpi_pattern: acpid

- name: General | Facts | Service | Linux
  set_fact:
    crond: cronie
    crond_pattern: cronie
  when: ansible_distribution == "Archlinux"
