---
# Define program names for service builtin.

- name: Facts | Workstation | Service | Linux
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
  when: ansible_system == "Linux"


- name: Facts | Workstation | Service | FreeBSD
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
    sshfs_leet_cmd: "sshfs ling@leet: /mnt/leet -o allow_other,_netdev"
  when: ansible_system == "FreeBSD"