---
# Define program names per OS for service builtin.

- name: Facts | Workstation | Service | Pop OS
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
  when: ansible_distribution == "Pop!_OS"


- name: Facts | Workstation | Service | Debian and Ubuntu
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
  when: ansible_distribution in ("Debian","Ubuntu")


- name: Facts | Workstation | Service | FreeBSD
  set_fact:
    cups: cups
    cups_pattern: cupsd
    cups_browse: cups-browsed
    cups_browse_pattern: cups-browsed
  when: ansible_system == "FreeBSD"