---
# Groups that do not come to all distros by default.

- name: General | Account Management | System Groups 
  group:
    name: "{{ item }}"
    system: yes
    state: present
  loop:
    - sudo
    - video
    - render
