---
# Mount shares that all systems should have.

- name: General | Account Management | Mounts | Create 1337 Folder
  file: 
    path: /mnt/leet
    state: directory
    mode: '0755'

- name: General | Account Management | Mounts | Create 1337 fstab Entry
  lineinfile:
    path: /etc/fstab
    regexp: '^ling@leet'
    line: "ling@leet: /mnt/leet fuse.sshfs defaults,_netdev,allow_other,delay_connect 0 0"
    state: present
    backup: yes

- name: General | Account Management | Mounts | Create 1337 fstab Comment
  lineinfile:
    path: /etc/fstab
    regexp: '^# MANAGED BY ANSIBLE | Leet Share'
    line: '# MANAGED BY ANSIBLE | Leet Share'
    state: present
    insertbefore: '^ling@leet'

- name: General | Account Management | Mounts | Mount All
  shell: mount -a
  args:
    warn: false
