---
# Mount shares that all systems should have.

- name: Mounts | Create 1337 Folder
  shell: mkdir -p /mnt/leet

- name: Mounts | Create fstab Entries
  blockinfile:
    path: /etc/fstab
    block: |
      ling@leet: /mnt/leet fuse.sshfs defaults,_netdev,allow_other,delay_connect 0 0
    backup: yes
