---
# Set up directory and files for specifying software needs rather than using hosts file.

- name: General | Account Management | Provisioning Configuration | Variables 1
  set_fact:
    prov_dir: "{{ user_root.home }}/.provision_config"

- name: General | Account Management | Provisioning Configuration | Variables 2
  set_fact:
    gen_file: "{{ prov_dir }}/general.ini"
    gui_file: "{{ prov_dir }}/workstation.ini"
    srv_file: "{{ prov_dir }}/server.ini"
    mnr_file: "{{ prov_dir }}/miner.ini"

- name: General | Account Management | Provisioning Configuration | Create Directory
  file: 
    path: "{{ prov_dir }}"
    state: directory
    mode: '0755'
  when: user_root.home != ""

- name: General | Account Management | Provisioning Configuration | Create General
  blockinfile:
    path: "{{ gen_file }}"
    block: |
      ;;;;;;; Available options - all require lowercase values ;;;;;;
      ;
      ;     branch : Provide the Github branch that the machine should poll.
      ;                Example: main, dev
      ;
      ; pentesting : Set to anything to install tools such as metasploit (nmap is already provided for reporting)
      ;                Example: true
      ;
    marker: '; {mark} MANAGED BY ANSIBLE | Generic Config'
    state: present
    create: yes
    backup: yes
  when: user_root.home != ""

# ini module not being recognized. Try it the lookup way.
#- name: General | Account Management | Provisioning Configuration | Load General 1
#  ini:
#    file: "{{ gen_file }}"
#    _terms: 
#      - branch
#      - pentesting
#  ignore_errors: yes
#
#- name: General | Account Management | Provisioning Configuration | Debug General 1
#  debug: 
#    var: "{{ item }}"
#  loop:
#    - branch
#    - pentesting
#  ignore_errors: yes
#
#- name: General | Account Management | Provisioning Configuration | Load General 2
#  ini:
#    file: "{{ gen_file }}"
#    _terms: "{{ item }}"
#  loop:
#    - branch
#    - pentesting
#  ignore_errors: yes
#
#- name: General | Account Management | Provisioning Configuration | Debug General 2
#  debug: 
#    var: "{{ item }}"
#  loop:
#    - branch
#    - pentesting
#  ignore_errors: yes

- name: General | Account Management | Provisioning Configuration | Load General 3
  set_fact:
    branch: "{{ lookup('ini', 'branch file={{gen_file}} default=main') }}"
    pentesting: "{{ lookup('ini', 'pentesting file={{gen_file}} default=false') }}"
  ignore_errors: yes

- name: General | Account Management | Provisioning Configuration | Debug General 3
  debug: 
    var: "{{ item }}"
  loop:
    - branch
    - pentesting
  ignore_errors: yes

## Holding off on these until concept is confirmed to work. ##
# TBD: Create Workstation

# TBD: Create Server

# TBD: Create Miner
