---
# Ensure the proper users have sudo access.

- name: General | Account Management | Sudo | Copy Ansible
  copy:
    src: sudoers_ansible
    dest: "{{ sudoers_install_dir }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0440

- name: General | Account Management | Sudo | Copy Sudo Group
  copy:
    src: sudoers_sudo
    dest: "{{ sudoers_install_dir }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0440