---
# Create users for both desktop and server machines.

# Scheduler
- name: General | Account Management | User | Ansible
  user:
    name: ansible
    comment: Ansible
    system: yes


# Superuser
- name: General | Account Management | User | Hyperling
  user:
    name: ling
    comment: Hyperling
    groups: 
      - sudo
    append: yes
    shell: "{{ bash_exec.stdout }}"
    create_home: yes
    generate_ssh_key: yes
    #password: "{{ ling_passwd }}"
