---
# Create users for both desktop and server machines.

# Scheduler
- name: Create User Ansible
  user:
    name: ansible
    comment: Ansible
    system: yes

# Get facts
- name: Locate bash
  shell: which bash
  register: bash_exec

# Superuser
- name: Create User Hyperling
  user:
    name: ling
    comment: Hyperling
    groups: 
      - sudo
    append: yes
    shell: "{{ bash_exec.stdout }}"
    create_home: yes
    generate_ssh_key: yes
    #password: "{{ ling_passwd }}"
