---
# Create users for both desktop and server machines.

# Scheduler
- name: Create User Ansible
  user:
    name: ansible
    comment: Ansible
    system: yes


# Superuser
- name: Create User Hyperling
  user:
    name: ling
    comment: Hyperling
    groups: 
      - sudo
    append: yes
    shell: /bin/bash
    create_home: yes
    generate_ssh_key: yes
