---
# Provide FreeBSD with a DE.

- name: Workstation | FreeBSD | GUI | Install UI Components
  package: 
    name:
    - xorg
    - gnome3
    - "{{ firefox_esr }}"
    - "{{ thunderbird }}"
    state: present

- name: Workstation | FreeBSD | GUI | Uninstall Bloat
  package: 
    name:
    - "{{ firefox }}"
    - "{{ evolution }}"
    state: absent

- name: Workstation | FreeBSD | GUI | Create rc.conf Entries
  blockinfile:
    path: /etc/rc.conf
    block: |
      dbus_enable="YES"
      hald_enable="YES"
      gnome_enable="YES"
      gdm_enable="YES"

      fusefs_enable="YES"
    backup: yes

- name: Workstation | FreeBSD | GUI | Create fstab Entries
  blockinfile:
    path: /etc/fstab
    block: |
      proc            /proc           procfs  rw      0       0
    backup: yes
